# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip -o ninja-linux.zip
    unzip ninja-linux.zip
    sudo cp -v ninja /usr/bin/
    echo "$PATH"
  displayName: Install Ninja

# CMake
# Build with the CMake cross-platform build system
- task: CMake@1
  inputs:
    cmakeArgs: -S "$(Build.SourcesDirectory)/vcpkg_manifest" -B "build" -G Ninja -DCMAKE_TOOLCHAIN_FILE="$(Build.SourcesDirectory)/vcpkg/scripts/buildsystems/vcpkg.cmake"
