# This is a basic workflow that is manually triggered

name: Manual workflow for installing MPI on Windows

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  install_mpi:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: download msmpi 10.0
      run: C:\msys64\usr\bin\wget.exe "https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe"
    - name: echo finished
      run: echo "Download finished"
    - name: install msmpi
      shell: cmd
      run: .\msmpisetup.exe -unattend -verbose
    - name: print dir
      shell: cmd
      run: |
        dir "C:\Program Files"
        dir "C:\Program Files\Microsoft MPI"
        dir "C:\Program Files\Microsoft MPI\Bin"
      
        
